_target_: src.trainer.Trainer
default_root_dir: ${paths.output_dir}

min_epochs: 1 # prevents early stopping
max_epochs: 120

validation_every_n_epochs: 1
test_every_n_epochs: 1

accelerator: cpu

deterministic: False
learning_rate: 1e-4
weight_decay: 1e-2